[build]
  command = "php construir.php"
  functions = "funciones/"
  publish = "publico/"
  [build.environment]
    PHP_VERSION = "7.4"

[context.production]
  command = "php construir.php"
  functions = "funciones/"
  publish = "publico/"
  [context.environment]
    PHP_VERSION = "7.4"


[context.deploy-preview]
  command = "php construir.php"
  functions = "funciones/"
  publish = "publico/"
  [context.environment]
    PHP_VERSION = "7.4"

[context.branch-deploy]
  command = "php construir.php"
  functions = "funciones/"
  publish = "publico/"
  [context.environment]
    PHP_VERSION = "7.4"
